### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module (at register-service-worker.js:3:1)

### ISSUE THREAD

**Issue by xiaoxixi6633** [yyx990803/register-service-worker#66]
Uncaught SyntaxError: Cannot use import statement outside a module (at register-service-worker.js:3:1)
![image](https://user-images.githubusercontent.com/15321829/209637633-f277c0f4-63c3-48e7-be49-5f60d337c63e.png)
![image](https://user-images.githubusercontent.com/15321829/209637682-b13fca2b-46c0-44a6-a3ad-5712fc7e3526.png)
![image](https://user-images.githubusercontent.com/15321829/209637715-2911cd72-7d2f-4b5b-8dd4-ca55f3218712.png)
![image](https://user-images.githubusercontent.com/15321829/209637741-78fedb74-eb6d-4c8f-ad76-68d7d4fba84e.png)
![image](https://user-images.githubusercontent.com/15321829/209637749-819d8581-0a49-4ac5-8672-935db4e13e2b.png)

**Comment by diego-rapoport** [comment]
I'm facing the same issue
